### ISSUE TITLE
Example does not compile

### ISSUE THREAD

**Issue by nick-bors** [BrianWiz/qevy#8]
Cloning the qevy project then running:
```
cargo run --example first_person --features="xpbd"
```
Fails to compile. It seems like there have been api changes since the example was written. For example, is no "open_time" property for the Door component.

**Comment by nick-bors** [comment]
Here are all the errors i got from compilation (with a few path fixes due to new api):
```
mover.start_translation field not existing 
mover.speed field not existing
door.triggered_time being an unknown field
```
I will try and fix the example and make a PR. Id love to use this project in my game!

**Comment by BrianWiz** [comment]
Hey @fami-fish thanks for reporting this, I'm having a hard time finding the time to maintain this project at the moment so a PR fixing this example would be very much appreciated!

**Comment by coreh** [comment]
👋 I have a PR for updating to Bevy 0.14, (#9) it also fixes the example
